image: golang:alpine

steps:
  - name: build
    actions:
      - echo "building step 1"
      - echo "building step 2"
  - parallel:
      - name: unit test
        except:
          - master
        actions:
          - echo "unit testing"
      - name: integration test
        only: [develop, release/*]
        actions:
          - echo "integration testing step 1"
          - echo "integration testing step 2"
  - name: deploy
    only:
      - release/*
    actions:
      - echo "do deploy"
