image: golang:alpine

steps:
  - name: build
    actions:
      - echo "building step 1"
      - echo "building step 2"
  - parallel:
      - name: unit test
        actions:
          - echo "unit testing"
      - name: integration test
        when: branch == develop
        actions:
          - echo "integration testing step 1"
          - echo "integration testing step 2"
  - name: deploy
    when: branch == release/*
    actions:
      - echo "do deploy"
