image: golang:alpine

variables:
  TEST_URL: http://example.com
  POSTGRES_PASSWORD: t@st!p@ssw0rd
  MYSQL_ROOT_PASSWORD: t@st!p@ssw0rd

services:
  - postgres:latest
  - nginx:latest
  - redis:alpine

steps:
  - name: build
    actions:
      - echo "building step 1" && go version
      - echo "building step 2"
  - parallel:
      - name: unit test
        except:
          - master
        actions:
          - echo "unit testing againest test url $TEST_URL and refereing to builtin var $NODE_NAME"
      - name: integration test
        only: [develop, release/*]
        actions:
          - apk add curl
          - while true; echo " sleepgin ... " ; do sleep 10; done;
          - echo "testing postgres" && curl postgres:5432
          - echo "testing nginx" && curl nginx:80
          - echo "testing redis" && exec 3<>/dev/tcp/redis/6379 && echo -e "PING\r\n" >&3 && head -c 7 <&3
  - name: deploy
    trigger: manual
    only:
      - release/*
    actions:
      - echo "do deploy"
